---
title: "ripasso"
author: "Alessandro Fusta Moro"
format: html
editor: visual
toc: true
toc-expand: true
toc-depth: 4
---

## Definizioni

#### Variabile

Una *variabile* è una caratteristica il cui valore può variare tra i soggetti di un campione o di una popolazione.

##### Campione casuale semplice

Un *campione casuale semplice* di $n$ soggetti di una popolazione è un campione che ha la medesima probabilità di essere selezionato di qualsiasi altro possibile campione avente dimensione $n$.

#### Probabilità

Nell'osservazione di un fenomeno aleatorio, la *probabilità* di un particolare esito è la proporzione di volte in cui quell'esito si verificherebbe in una sequenza arbitrariamente lunga di osservazioni simili, sotto le stesse condizioni.

#### Spazio campionario

Per un fenomeno aleatorio, l'insieme di tutti i possibili esiti è detto *spazio campionario*.

#### Variabile aleatoria

Per un fenomeno aleatorio, una *variabile aleatoria* è una funzione che assegna un valore numerico a ogni punto dello spazio campionario. È prassi comune utilizzare le lettere maiuscole per rappresentare le variabili aleatorie e le minuscole per i singoli possibili valori.

#### Distribuzione di probabilità

Una *distribuzione di probabilità* elenca i possibili valori di una variabile aleatoria e le rispettive probabilità. La *funzione di distribuzione di probabilità* $f(x)$ restituisce la probabilità che la variabile aleatoria $X$ restituisca il valore $x$. L'area sottesa da tale curva $f(x)$ equivale a 1 ovvero la probabilità dello spazio campionario. La *funzione di distribuzione cumulata* $F(x)$ restituisce la probabilità che la variabile aleatoria $X$ sia minore o uguale del valore $x$.

$$f(x)=P(X=x) \qquad \text{con} \quad \int_xf(x)=1$$ $$F(x)=P(X \leq x) \qquad \text{con} \quad F(+ \infty)=1$$

